name: Makefile CI

on:
  push:
    branches: [ "vnd_k6877v1_64_k419-user-12-SP1A.210812.016-1702624828533-release-keys" ]
  pull_request:
    branches: [ "vnd_k6877v1_64_k419-user-12-SP1A.210812.016-1702624828533-release-keys" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
